version: "3.1"

volumes:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled_plugins:

services:
  postgres:
    image: postgres:10.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${SONARQUBE_JDBC_USER:-sonar} 
      POSTGRES_PASSWORD: ${SONARQUBE_JDBC_PASSWORD:-sonar} 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonarqube:
    image: alapshin/sonarqube
    container_name: sonarqube
    depends_on: 
      - postgres
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: ${SONARQUBE_JDBC_USER:-sonar}
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_JDBC_PASSWORD:-sonar}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins

